version: '3.5'
services:
  api1: # API - Instância 01
    image: api
    hostname: "inst1"
    depends_on:
      db:
        condition: service_completed_successfully
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - rinha-backend-arch

  api2: # API - Instância 01
    image: api
    hostname: "inst2"
    depends_on:
      db:
        condition: service_completed_successfully
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - rinha-backend-arch

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - rinha-backend-arch

  db: # Banco de dados
    image: mysql
    healthcheck:

    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    networks:
      - rinha-backend-arch
networks:
  rinha-backend-arch: